# Generated by Django 3.1.7 on 2021-05-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('correo', models.EmailField(max_length=254, verbose_name='Email')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(help_text='<span class="font-italic" style="font-size: 0.9rem">Nombre de la calle y número</span>', max_length=200, verbose_name='Calle y Número')),
                ('colonia', models.CharField(help_text='<span class="font-italic" style="font-size: 0.9rem">Nombre de la colonia o fraccionamiento</span>', max_length=200, verbose_name='Colonia o Fraccionamiento')),
                ('total', models.DecimalField(decimal_places=2, help_text='<span class="text-danger" style="font-size: 0.9rem">Cantidad a pagar por su pedido</span>', max_digits=8, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
